name: gravatar
version: 1.1.0
authors:
- Nik Graf <nik@blossom.io>
- Thomas Schranz <thomas@blossom.io>
description: Generate Gravatar Image Urls
homepage: https://github.com/blossom/gravatar
dependencies:
  unittest: any
