name: gravatar
version: 1.2.1
authors:
- Nik Graf <nik@blossom.io>
- Thomas Schranz <thomas@blossom.io>
description: Generate Gravatar Image Urls
homepage: https://github.com/blossom/gravatar
documentation: http://blossom.github.com/gravatar/doc/gravatar/Gravatar.html
dependencies:
  crypto: '>=0.5.13 <0.5.14'
dev_dependencies:
  unittest: '>=0.5.13 <0.5.14'
